import os
import json
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google.auth.transport.requests import Request

def upload_to_youtube(file_path, title, token_path):
    scopes = ["https://www.googleapis.com/auth/youtube.upload"]

    # Load client secret from environment
    client_secret_str = os.environ["CLIENT_SECRET_JSON"]
    client_config = json.loads(client_secret_str)

    # Load per-channel token
    creds = Credentials.from_authorized_user_file(token_path, scopes)

    # Refresh token if needed
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
        with open(token_path, "w") as f:
            f.write(creds.to_json())

    youtube = build("youtube", "v3", credentials=creds)

    request_body = {
        "snippet": {
            "title": title[:100],
            "description": "Generated by AI",
            "tags": ["reddit", "ai", "shorts"],
            "categoryId": "24"
        },
        "status": {
            "privacyStatus": "public",
            "madeForKids": False
        }
    }

    media = MediaFileUpload(file_path)
    res = youtube.videos().insert(
        part="snippet,status",
        body=request_body,
        media_body=media
    ).execute()

    print(f"✅ Uploaded to channel {res['id']}")
