import os
import json
import pickle
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

def upload_to_youtube(file_path, title):
    scopes = ["https://www.googleapis.com/auth/youtube.upload"]

    # Load client secret from environment variable
    client_secret_str = os.environ["CLIENT_SECRET_JSON"]
    client_config = json.loads(client_secret_str)

    # Setup OAuth flow from loaded config
    flow = Flow.from_client_config(client_config, scopes=scopes, redirect_uri='http://localhost:8080/')
    credentials = flow.run_local_server(port=8080)

    # Save the credentials for future use
    with open("token.pkl", "wb") as token_file:
        pickle.dump(credentials, token_file)

    # Build YouTube API client
    youtube = build("youtube", "v3", credentials=credentials)

    # Prepare the request body
    request_body = {
        "snippet": {
            "title": title[:100],
            "description": "Generated by AI",
            "tags": ["reddit stories", "ai generated", "shorts"],
            "categoryId": "24"
        },
        "status": {
            "privacyStatus": "public",
            "madeForKids": False
        }
    }

    # Upload the video
    media_file = MediaFileUpload(file_path)
    response = youtube.videos().insert(
        part="snippet,status",
        body=request_body,
        media_body=media_file
    ).execute()

    print("✅ Upload successful:", response["id"])
